export const GET_SERVICE_PROVIDER_SERVICE =
  "GET SERVICE PROVIDER SERVICE [IDEEZA][TECHNICIAN][MANAGEMENT][SERVICE][PROVIDER][SERVICES]";
export const GET_SERVICE_PROVIDER_SERVICE_SUCCESS =
  "GET SERVICE PROVIDER SERVICE SUCCESS [IDEEZA][TECHNICIAN][MANAGEMENT][SERVICE][PROVIDER][SERVICES]";
export const TOGGLE_LOADER =
  "TOGGLE_LOADER [IDEEZA][TECHNICIAN][MANAGEMENT][SERVICE][PROVIDER][SERVICES]";

export const onService = (payload) => {
  return {
    type: GET_SERVICE_PROVIDER_SERVICE,
    payload,
  };
};
export const onserviceSuccess = (payload) => {
  return {
    type: GET_SERVICE_PROVIDER_SERVICE_SUCCESS,
    payload,
  };
};
